name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  github-token:  # id of input
    description: 'The token to use to write tags'
    required: true
    default: undefined
runs:
  using: 'node16'
  main: 'dist/index.js'
