name: Push Release Branch

on:
  workflow_dispatch:

  push:
    tags:
      - v*.*.*
      - "!v*.*.*-*"

jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.personal_token }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.personal_token }}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Create release branch
        run: ./.github/workflows/create-release-branch.sh


