name: "units-test"
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - labeled

  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - uses: ./
      with:
        github-token: ${{ secrets.TOKEN }}
        prerelease-label: 'prease-release-me'
        major-release-label: 'major-tom'
        minor-release-label: 'minor-tom'
